export const mettingListData: Array<MettingListType> = [
  {
    city: 'Inruwa',
    day: 'Friday',
    name: 'Antim Sahara Home Group',
    from: '04:00',
    to: '05:00',
    time: 'pm',
    location: 'Bhagwati Ma. Vi, Inaruwa-1',
    gmap: '',
    img: 'https://i0.wp.com/nacentralohio.org/wp-content/uploads/2018/05/cropped-cropped-default_nalogo-1.jpg',
  },
  {
    city: 'Itahari',
    day: 'Saturday',
    name: 'Sandesh Home Group',
    from: '04:00',
    to: '05:00',
    time: 'pm',
    location: 'Green peace academy',
    gmap: 'https://maps.app.goo.gl/L82rWN6xsnZo6Ae77',
    img: '',
  },
  {
    city: 'Itahari',
    day: 'Thursday',
    name: "God's Will Home Group",
    from: '04:15',
    to: '05:15',
    time: 'pm',
    location: 'Green peace academy',
    gmap: 'https://maps.app.goo.gl/L82rWN6xsnZo6Ae77',
    img: '',
  },
  {
    city: 'Jhumka',
    day: 'Friday',
    name: 'Voice Home Group',
    from: '04:00',
    to: '05:15',
    time: 'pm',
    location: 'Red cross bhawaan jhumka',
    gmap: '',
    img: '',
  },
  {
    city: 'Belbari',
    day: 'Tuesday',
    name: 'Journey Continues Home Group',
    from: '03:30',
    to: '04:30',
    time: 'pm',
    location: 'Bahumukhi Campus Puranobelbari',
    gmap: '',
    img: '',
  },
  {
    city: 'Belbari',
    day: 'Saturday',
    name: 'Wisdom Home Group',
    from: '03:30',
    to: '04:30',
    time: 'pm',
    location: 'Shree Prathamik ma vi, Karam dada line',
    gmap: '',
    img: '',
  },
];
